FROM handsonsecurity/seedemu-ethereum

# Install the necessary network attack tools and Python
RUN apt-get update && apt-get install -y \
    iptables \
    dsniff \
    python3 \
    python3-pip \
    iproute2 \
    net-tools \
    nano


