version: "3.4"
services:
    new_ethereum_node:
        build:
            context: ./new_eth_node
        image: new_ethereum_node
        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m
    707ec7fa5d3740bf02573cbd0b37e6ea:
        build:
            context: .
            dockerfile: dummies/707ec7fa5d3740bf02573cbd0b37e6ea
        image: 707ec7fa5d3740bf02573cbd0b37e6ea
        cpus: 0.2
        mem_limit: 512m
        mem_reservation: 128m
        depends_on:
            - new_ethereum_node

    98a2693c996c2294358552f48373498d:
        build:
            context: .
            dockerfile: dummies/98a2693c996c2294358552f48373498d
        image: 98a2693c996c2294358552f48373498d
        cpus: 0.2
        mem_limit: 512m
        mem_reservation: 128m

    39e016aa9e819f203ebc1809245a5818:
        build:
            context: .
            dockerfile: dummies/39e016aa9e819f203ebc1809245a5818
        image: 39e016aa9e819f203ebc1809245a5818
        cpus: 0.2
        mem_limit: 512m
        mem_reservation: 128m

    24e044b795288bc851bbf81da183e7a9:
        build:
            context: .
            dockerfile: dummies/24e044b795288bc851bbf81da183e7a9
        image: 24e044b795288bc851bbf81da183e7a9
        cpus: 0.2
        mem_limit: 512m
        mem_reservation: 128m


    hnode_160_host_0:
        build: ./hnode_160_host_0
        container_name: as160h-Ethereum-POW-00-Miner-BootNode-10.160.0.71
        depends_on:
            - 24e044b795288bc851bbf81da183e7a9
        cap_add:
            - ALL

        privileged: true
        cpus: 1.0
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.71

        volumes:
            - ./eth_startup.py:/eth_startup.py:ro
            - ./traffic_gen.py:/traffic_gen.py:ro

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "160"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_0"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POW-00-Miner-BootNode"
            org.seedsecuritylabs.seedemu.meta.class: "[\"Miner\", \"BootNode\", \"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "1"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"bootnode\", \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.71/24"

        environment:
            - CONTAINER_NAME=as160h-Ethereum-POW-00-Miner-BootNode-10.160.0.71
            - SENDER_ACCOUNTS=0x1be9288F9a7D2F809250f15c487E3a5A9Cf71f4F,0xA403f63AD02a557D5DDCBD5F5af9A7627C591034

    hnode_160_host_1:
        build: ./hnode_160_host_1
        container_name: as160h-host_1-10.160.0.72
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.72

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "160"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_1"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.72/24"

        environment:
            - CONTAINER_NAME=as160h-host_1-10.160.0.72

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m


    hnode_160_host_2:
        build: ./hnode_160_host_2
        container_name: as160h-host_2-10.160.0.73
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.73

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "160"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_2"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.73/24"

        environment:
            - CONTAINER_NAME=as160h-host_2-10.160.0.73

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m


    brdnode_160_router0:
        build: ./brdnode_160_router0
        container_name: as160brd-router0-10.160.0.254
        depends_on:
            - 39e016aa9e819f203ebc1809245a5818
        cap_add:
            - ALL

        privileged: true
        networks:
            net_160_net0:
                ipv4_address: 10.160.0.254

            net_ix_ix103:
                ipv4_address: 10.103.0.160


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "160"
            org.seedsecuritylabs.seedemu.meta.nodename: "router0"
            org.seedsecuritylabs.seedemu.meta.role: "BorderRouter"
            org.seedsecuritylabs.seedemu.meta.loopback_addr: "10.0.0.1"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.160.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix103"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.103.0.160/24"

        environment:
            - CONTAINER_NAME=as160brd-router0-10.160.0.254

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    hnode_161_host_0:
        build: ./hnode_161_host_0
        container_name: as161h-Ethereum-POW-01-Miner-10.161.0.71
        depends_on:
            - 24e044b795288bc851bbf81da183e7a9
        cap_add:
            - ALL

        privileged: true
        cpus: 1.0
        networks:
            net_161_net0:
                ipv4_address: 10.161.0.71

        volumes:
            - ./eth_startup.py:/eth_startup.py:ro
            - ./traffic_gen.py:/traffic_gen.py:ro

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "161"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_0"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POW-01-Miner"
            org.seedsecuritylabs.seedemu.meta.class: "[\"Miner\", \"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "2"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.161.0.71/24"

        environment:
            - CONTAINER_NAME=as161h-Ethereum-POW-01-Miner-10.161.0.71
            - SENDER_ACCOUNTS=0x1081c645CC8c21EfbB0114eAc5fcDBE01a1a4b19,0xa6bBf9891a0689Fe91d9c1538478b95effe0a57A



    hnode_161_host_1:
        build: ./hnode_161_host_1
        container_name: as161h-host_1-10.161.0.72
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_161_net0:
                ipv4_address: 10.161.0.72

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "161"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_1"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.161.0.72/24"

        environment:
            - CONTAINER_NAME=as161h-host_1-10.161.0.72

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    hnode_161_host_2:
        build: ./hnode_161_host_2
        container_name: as161h-host_2-10.161.0.73
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_161_net0:
                ipv4_address: 10.161.0.73

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "161"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_2"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.161.0.73/24"

        environment:
            - CONTAINER_NAME=as161h-host_2-10.161.0.73

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    brdnode_161_router0:
        build: ./brdnode_161_router0
        container_name: as161brd-router0-10.161.0.254
        depends_on:
            - 39e016aa9e819f203ebc1809245a5818
        cap_add:
            - ALL

        privileged: true
        networks:
            net_161_net0:
                ipv4_address: 10.161.0.254

            net_ix_ix103:
                ipv4_address: 10.103.0.161


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "161"
            org.seedsecuritylabs.seedemu.meta.nodename: "router0"
            org.seedsecuritylabs.seedemu.meta.role: "BorderRouter"
            org.seedsecuritylabs.seedemu.meta.loopback_addr: "10.0.0.2"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.161.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix103"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.103.0.161/24"

        environment:
            - CONTAINER_NAME=as161brd-router0-10.161.0.254

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    hnode_162_host_0:
        build: ./hnode_162_host_0
        container_name: as162h-Ethereum-POW-02-Miner-10.162.0.71
        depends_on:
            - 24e044b795288bc851bbf81da183e7a9
        cap_add:
            - ALL

        privileged: true
        cpus: 1.0
        networks:
            net_162_net0:
                ipv4_address: 10.162.0.71

        volumes:
            - ./eth_startup.py:/eth_startup.py:ro
            - ./traffic_gen.py:/traffic_gen.py:ro

        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "162"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_0"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POW-02-Miner"
            org.seedsecuritylabs.seedemu.meta.class: "[\"Miner\", \"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "3"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "POW"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.162.0.71/24"

        environment:
            - CONTAINER_NAME=as162h-Ethereum-POW-02-Miner-10.162.0.71
            - SENDER_ACCOUNTS=0x8c400205fDb103431F6aC7409655ad3cf8f6d007,0x9105A373ce1d01B517aA54205A5E4c70FA9f34Fe



    hnode_162_host_1:
        build: ./hnode_162_host_1
        container_name: as162h-host_1-10.162.0.72
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_162_net0:
                ipv4_address: 10.162.0.72

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "162"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_1"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.162.0.72/24"

        environment:
            - CONTAINER_NAME=as162h-host_1-10.162.0.72

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    hnode_162_host_2:
        build: ./hnode_162_host_2
        container_name: as162h-host_2-10.162.0.73
        depends_on:
            - 98a2693c996c2294358552f48373498d
        cap_add:
            - ALL

        privileged: true
        networks:
            net_162_net0:
                ipv4_address: 10.162.0.73

        volumes:
            - ./traffic_gen.py:/traffic_gen.py:ro


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "162"
            org.seedsecuritylabs.seedemu.meta.nodename: "host_2"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.162.0.73/24"

        environment:
            - CONTAINER_NAME=as162h-host_2-10.162.0.73

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    hnode_162_new_eth_node:
        build: ./hnode_162_new_eth_node
        container_name: as162h-new_eth_node-10.162.0.74
        depends_on:
            - 707ec7fa5d3740bf02573cbd0b37e6ea
        cap_add:
            - ALL

        privileged: true
        networks:
            net_162_net0:
                ipv4_address: 10.162.0.74


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "162"
            org.seedsecuritylabs.seedemu.meta.nodename: "new_eth_node"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.162.0.74/24"

        environment:
            - CONTAINER_NAME=as162h-new_eth_node-10.162.0.74
            - SYNFLOOD=${SYNFLOOD:-false}
            - ECLIPSE_ARP=${ECLIPSE_ARP:-false}
            - ECLIPSE_BGP=${ECLIPSE_BGP:-false}

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    brdnode_162_router0:
        build: ./brdnode_162_router0
        container_name: as162brd-router0-10.162.0.254
        depends_on:
            - 39e016aa9e819f203ebc1809245a5818
        cap_add:
            - ALL

        privileged: true
        networks:
            net_162_net0:
                ipv4_address: 10.162.0.254

            net_ix_ix103:
                ipv4_address: 10.103.0.162


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "162"
            org.seedsecuritylabs.seedemu.meta.nodename: "router0"
            org.seedsecuritylabs.seedemu.meta.role: "BorderRouter"
            org.seedsecuritylabs.seedemu.meta.loopback_addr: "10.0.0.3"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "net0"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.162.0.254/24"
            org.seedsecuritylabs.seedemu.meta.net.1.name: "ix103"
            org.seedsecuritylabs.seedemu.meta.net.1.address: "10.103.0.162/24"

        environment:
            - CONTAINER_NAME=as162brd-router0-10.162.0.254

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m



    rs_ix_ix103:
        build: ./rs_ix_ix103
        container_name: as103brd-ix103-10.103.0.103
        depends_on:
            - 39e016aa9e819f203ebc1809245a5818
        cap_add:
            - ALL

        privileged: true
        networks:
            net_ix_ix103:
                ipv4_address: 10.103.0.103


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "103"
            org.seedsecuritylabs.seedemu.meta.nodename: "ix103"
            org.seedsecuritylabs.seedemu.meta.role: "Route Server"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "ix103"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.103.0.103/24"

        environment:
            - CONTAINER_NAME=as103brd-ix103-10.103.0.103

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m


    seedemu-ether-client:
        image: handsonsecurity/seedemu-multiarch-etherview:2.0
        container_name: seedemu_ether_view
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 5000:5000/tcp

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m


    seedemu_internet_map:
        image: handsonsecurity/seedemu-internetmap:2.0
        container_name: seedemu_internet_map
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        privileged: true
        ports:
            - 8080:8080/tcp

        cpus: 1.5
        mem_limit: 512m
        mem_reservation: 128m


networks:
    net_160_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.160.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "160"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.160.0.0/24"

    net_161_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.161.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "161"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.161.0.0/24"

    net_162_net0:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.162.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "local"
            org.seedsecuritylabs.seedemu.meta.scope: "162"
            org.seedsecuritylabs.seedemu.meta.name: "net0"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.162.0.0/24"

    net_ix_ix103:
        driver_opts:
            com.docker.network.driver.mtu: 1500
        ipam:
            config:
                - subnet: 10.103.0.0/24
        labels:
            org.seedsecuritylabs.seedemu.meta.type: "global"
            org.seedsecuritylabs.seedemu.meta.scope: "ix"
            org.seedsecuritylabs.seedemu.meta.name: "ix103"
            org.seedsecuritylabs.seedemu.meta.prefix: "10.103.0.0/24"
            org.seedsecuritylabs.seedemu.meta.displayname: "Miami-103"




