"""
infer.py
========
Load pre-trained classifier and/or outlier-detector models and evaluate them
on a new PCAP file.  Prints per-model metrics and (optionally) saves a CSV of
per-packet predictions.

Usage
-----
    # Evaluate every .joblib model found in models/
    python infer.py capture.pcap --model-dir models/

    # Evaluate specific models
    python infer.py capture.pcap --models models/rf.joblib models/iforest.joblib

    # Override the malicious host identity used for ground-truth labelling
    python infer.py capture.pcap --model-dir models/ \\
        --malicious-ip 192.168.1.99 --malicious-mac 00:11:22:33:44:55

    # Supply a known-good IP whitelist (unknown IPs are also labelled malicious)
    python infer.py capture.pcap --model-dir models/ \\
        --known 10.0.0.1 10.0.0.2 --malicious-ip 10.0.0.99

    # Save per-packet predictions to a CSV
    python infer.py capture.pcap --model-dir models/ --out predictions.csv

Notes
-----
* Scaler discovery: for a model saved as <name>.joblib, the script looks for
  <name>_scaler.joblib in the same directory.  If found it is applied
  automatically.  This mirrors the convention used by classify.py and
  detect_outliers.py.

* Outlier detectors (iforest, ocsvm, lof, envelope) are recognised by name
  prefix.  All other models are treated as classifiers (predict_proba).  You
  can force the type with --force-type {classifier,detector}.

* Ground-truth labels are generated by the same feature_extraction pipeline
  used during training.  The --malicious-ip and --malicious-mac flags patch
  the module-level constants in feature_extraction so the labelling logic is
  identical to training — just with a different host identity.
"""

import argparse
import importlib
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix,
)

# ---------------------------------------------------------------------------
# Outlier-detector name prefixes (used to auto-detect model type)
# ---------------------------------------------------------------------------
_DETECTOR_PREFIXES = ("iforest", "ocsvm", "lof", "envelope")


def _is_detector(name: str) -> bool:
    return any(name.startswith(p) for p in _DETECTOR_PREFIXES)


# ---------------------------------------------------------------------------
# Feature extraction with patched labelling constants
# ---------------------------------------------------------------------------

def extract_features_patched(
    pcap_path: str,
    malicious_ip: str | None,
    malicious_mac: str | None,
    known_addresses: list[str] | None,
    window_seconds: float,
) -> pd.DataFrame:
    """
    Call extract_features with temporarily patched MALICIOUS_IP / MALICIOUS_MAC
    module-level constants so ground-truth labels reflect the new capture's
    attacker host rather than the one hard-coded during development.

    The patch is applied via importlib so it does not permanently alter the
    module for any other code sharing this interpreter session.
    """
    import ids_2.feature_extraction as fe_mod

    original_ip  = fe_mod.MALICIOUS_IP
    original_mac = fe_mod.MALICIOUS_MAC

    try:
        if malicious_ip is not None:
            fe_mod.MALICIOUS_IP = malicious_ip
        if malicious_mac is not None:
            # Scapy normalises MACs to lowercase; mirror that here.
            fe_mod.MALICIOUS_MAC = malicious_mac.lower()

        df = fe_mod.extract_features(
            pcap_path,
            known_addresses=known_addresses,
            window_seconds=window_seconds,
        )
    finally:
        # Always restore originals, even if extraction raises.
        fe_mod.MALICIOUS_IP  = original_ip
        fe_mod.MALICIOUS_MAC = original_mac

    return df


# ---------------------------------------------------------------------------
# Model loading helpers
# ---------------------------------------------------------------------------

def _discover_models(model_dir: Path) -> list[Path]:
    """Return all *.joblib files in model_dir that are NOT scaler files."""
    return sorted(
        p for p in model_dir.glob("*.joblib")
        if not p.stem.endswith("_scaler")
    )


def _load_model_and_scaler(model_path: Path) -> tuple:
    """Load a model and, if present, its companion scaler."""
    model  = joblib.load(model_path)
    scaler_path = model_path.with_name(model_path.stem + "_scaler.joblib")
    scaler = joblib.load(scaler_path) if scaler_path.exists() else None
    return model, scaler


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate(
    model,
    scaler,
    X: np.ndarray,
    y: np.ndarray,
    name: str,
    force_type: str | None,
) -> dict:
    """
    Run inference and compute metrics.  Returns a result dict.

    For classifiers  : uses predict_proba for AUC.
    For detectors    : uses decision_function (negated so higher = more anomalous).
    """
    Xs = scaler.transform(X) if scaler is not None else X

    # Determine model type
    if force_type == "classifier":
        as_detector = False
    elif force_type == "detector":
        as_detector = True
    else:
        as_detector = _is_detector(name)

    if as_detector:
        raw_pred = model.predict(Xs)
        y_pred   = (raw_pred == -1).astype(int)
        y_score  = -model.decision_function(Xs)
        kind     = "detector"
    else:
        y_pred  = model.predict(Xs)
        y_score = model.predict_proba(Xs)[:, 1]
        kind    = "classifier"

    auc  = roc_auc_score(y, y_score)
    f1   = f1_score(y, y_pred,  zero_division=0)
    prec = precision_score(y, y_pred, zero_division=0)
    rec  = recall_score(y, y_pred,  zero_division=0)
    cm   = confusion_matrix(y, y_pred)
    report = classification_report(
        y, y_pred, target_names=["normal", "malicious"], digits=3
    )

    return {
        "name":      name,
        "kind":      kind,
        "y_pred":    y_pred,
        "y_score":   y_score,
        "auc":       auc,
        "f1":        f1,
        "precision": prec,
        "recall":    rec,
        "cm":        cm,
        "report":    report,
    }


def print_result(r: dict) -> None:
    sep = "=" * (len(r["name"]) + 8)
    print(sep)
    print(f"  {r['name'].upper()}  [{r['kind']}]")
    print(sep)
    print(r["report"])
    cm = r["cm"]
    print(f"  Confusion matrix:")
    print(f"    TN={cm[0,0]:>6,}  FP={cm[0,1]:>6,}")
    print(f"    FN={cm[1,0]:>6,}  TP={cm[1,1]:>6,}")
    print(f"  ROC-AUC  : {r['auc']:.4f}")
    print(f"  F1       : {r['f1']:.4f}")
    print(f"  Precision: {r['precision']:.4f}")
    print(f"  Recall   : {r['recall']:.4f}")
    print()


def print_summary(results: list[dict]) -> None:
    header = f"{'MODEL':<20} {'TYPE':<12} {'AUC':>7} {'F1':>7} {'PREC':>7} {'REC':>7}"
    print("=" * len(header))
    print("  SUMMARY")
    print("=" * len(header))
    print(header)
    print("-" * len(header))
    for r in sorted(results, key=lambda x: x["auc"], reverse=True):
        print(
            f"{r['name']:<20} {r['kind']:<12} "
            f"{r['auc']:>7.4f} {r['f1']:>7.4f} "
            f"{r['precision']:>7.4f} {r['recall']:>7.4f}"
        )
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate saved IDS models on a new PCAP file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # ---- input -----------------------------------------------------------------
    parser.add_argument("pcap", help="Path to .pcap / .pcapng file to evaluate")

    model_src = parser.add_mutually_exclusive_group(required=True)
    model_src.add_argument(
        "--model-dir", type=Path, metavar="DIR",
        help="Directory containing *.joblib model files (scaler files auto-discovered)")
    model_src.add_argument(
        "--models", nargs="+", type=Path, metavar="FILE",
        help="One or more explicit *.joblib model file paths")

    # ---- ground-truth labelling ------------------------------------------------
    parser.add_argument(
        "--malicious-ip", default=None, metavar="IP",
        help="IP address of the attacker host in this capture "
             "(overrides the hard-coded constant in feature_extraction.py)")
    parser.add_argument(
        "--malicious-mac", default=None, metavar="MAC",
        help="MAC address of the attacker host in this capture "
             "(overrides the hard-coded constant in feature_extraction.py)")
    parser.add_argument(
        "--known", nargs="*", default=None, metavar="IP",
        help="Whitelist of known-good IP addresses; traffic to/from any "
             "other IP is labelled malicious")

    # ---- feature extraction ----------------------------------------------------
    parser.add_argument(
        "--window", type=float, default=1.0,
        help="Rolling-feature look-back window in seconds (default: 1.0)")

    # ---- inference control -----------------------------------------------------
    parser.add_argument(
        "--force-type", choices=["classifier", "detector"], default=None,
        help="Override automatic model-type detection (classifier vs detector). "
             "Applies to ALL loaded models.")

    # ---- output ----------------------------------------------------------------
    parser.add_argument(
        "--out", type=Path, default=None, metavar="CSV",
        help="If set, save a CSV of per-packet predictions to this path. "
             "Each model adds a <name>_pred and <name>_score column.")

    args = parser.parse_args()

    # ---- resolve model paths ---------------------------------------------------
    if args.model_dir is not None:
        model_paths = _discover_models(args.model_dir)
        if not model_paths:
            sys.exit(f"No *.joblib model files found in {args.model_dir}")
        print(f"Found {len(model_paths)} model(s) in {args.model_dir}:")
        for p in model_paths:
            print(f"  {p.name}")
        print()
    else:
        model_paths = args.models
        missing = [p for p in model_paths if not p.exists()]
        if missing:
            sys.exit(f"Model file(s) not found: {missing}")

    # ---- feature extraction ----------------------------------------------------
    print(f"[1/3] Extracting features from {args.pcap} …")
    if args.malicious_ip:
        print(f"      Malicious IP  : {args.malicious_ip}")
    if args.malicious_mac:
        print(f"      Malicious MAC : {args.malicious_mac}")

    try:
        df = extract_features_patched(
            pcap_path=args.pcap,
            malicious_ip=args.malicious_ip,
            malicious_mac=args.malicious_mac,
            known_addresses=args.known,
            window_seconds=args.window,
        )
    except Exception as exc:
        sys.exit(f"Feature extraction failed: {exc}")

    feature_cols = [c for c in df.columns if c != "label"]
    X = df[feature_cols].values.astype(np.float32)
    y = df["label"].values

    n_total = len(y)
    n_pos   = int(y.sum())
    print(f"      {n_total:,} packets  |  {n_pos:,} malicious ({100*n_pos/n_total:.1f}%)\n")

    if n_pos == 0 or n_pos == n_total:
        sys.exit("Only one class present in the ground-truth labels — "
                 "check --malicious-ip / --malicious-mac / --known.")

    # ---- load models and run inference -----------------------------------------
    print(f"[2/3] Running inference with {len(model_paths)} model(s) …\n")

    results       = []
    pred_columns  = {}     # name -> (y_pred, y_score)

    for model_path in model_paths:
        name = model_path.stem
        try:
            model, scaler = _load_model_and_scaler(model_path)
        except Exception as exc:
            print(f"  WARNING: could not load {model_path.name}: {exc}")
            continue

        scaler_note = f" (+ scaler)" if scaler is not None else ""
        print(f"  Evaluating {name}{scaler_note} …")

        try:
            r = evaluate(model, scaler, X, y, name, args.force_type)
        except Exception as exc:
            print(f"  WARNING: inference failed for {name}: {exc}\n")
            continue

        results.append(r)
        pred_columns[name] = (r["y_pred"], r["y_score"])

    if not results:
        sys.exit("All models failed — nothing to report.")

    # ---- print results ---------------------------------------------------------
    print(f"\n[3/3] Results\n")
    for r in results:
        print_result(r)

    if len(results) > 1:
        print_summary(results)

    # ---- optional CSV output ---------------------------------------------------
    if args.out is not None:
        out_df = df[feature_cols].copy()
        out_df["label"] = y
        for name, (preds, scores) in pred_columns.items():
            out_df[f"{name}_pred"]  = preds
            out_df[f"{name}_score"] = scores
        out_df.to_csv(args.out, index=False)
        print(f"Per-packet predictions saved → {args.out.resolve()}")


if __name__ == "__main__":
    main()